- name: create common namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.name }}"
        labels:
          prometheus: "{{ item.prometheus }}"
  loop: "{{ namespaces }}"
